// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v4.23.3
// source: pod/v1/pod.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPodAddPod = "/api.pod.v1.Pod/AddPod"

type PodHTTPServer interface {
	AddPod(context.Context, *PodInfo) (*Response, error)
}

func RegisterPodHTTPServer(s *http.Server, srv PodHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/pod/add", _Pod_AddPod0_HTTP_Handler(srv))
}

func _Pod_AddPod0_HTTP_Handler(srv PodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PodInfo
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPodAddPod)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddPod(ctx, req.(*PodInfo))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type PodHTTPClient interface {
	AddPod(ctx context.Context, req *PodInfo, opts ...http.CallOption) (rsp *Response, err error)
}

type PodHTTPClientImpl struct {
	cc *http.Client
}

func NewPodHTTPClient(client *http.Client) PodHTTPClient {
	return &PodHTTPClientImpl{client}
}

func (c *PodHTTPClientImpl) AddPod(ctx context.Context, in *PodInfo, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/v1/pod/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPodAddPod))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
