// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v4.23.3
// source: podapi/v1/podapi.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v1 "github.com/zbnzl/paas-pod/api/pod/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPodApiAddPod = "/api.podApi.v1.PodApi/AddPod"
const OperationPodApiCall = "/api.podApi.v1.PodApi/Call"
const OperationPodApiDeletePodById = "/api.podApi.v1.PodApi/DeletePodById"
const OperationPodApiFindPodById = "/api.podApi.v1.PodApi/FindPodById"
const OperationPodApiUpdatePod = "/api.podApi.v1.PodApi/UpdatePod"

type PodApiHTTPServer interface {
	AddPod(context.Context, *v1.PodInfo) (*v1.Response, error)
	// Call默认接口
	Call(context.Context, *Request) (*Response, error)
	DeletePodById(context.Context, *v1.PodId) (*v1.Response, error)
	FindPodById(context.Context, *v1.PodId) (*v1.PodInfo, error)
	UpdatePod(context.Context, *v1.PodInfo) (*v1.Response, error)
}

func RegisterPodApiHTTPServer(s *http.Server, srv PodApiHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/pod", _PodApi_FindPodById0_HTTP_Handler(srv))
	r.POST("/v1/pod", _PodApi_AddPod1_HTTP_Handler(srv))
	r.DELETE("/v1/pod", _PodApi_DeletePodById0_HTTP_Handler(srv))
	r.PUT("/v1/pod", _PodApi_UpdatePod1_HTTP_Handler(srv))
	r.GET("/v1", _PodApi_Call0_HTTP_Handler(srv))
}

func _PodApi_FindPodById0_HTTP_Handler(srv PodApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.PodId
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPodApiFindPodById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindPodById(ctx, req.(*v1.PodId))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.PodInfo)
		return ctx.Result(200, reply)
	}
}

func _PodApi_AddPod1_HTTP_Handler(srv PodApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.PodInfo
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPodApiAddPod)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddPod(ctx, req.(*v1.PodInfo))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Response)
		return ctx.Result(200, reply)
	}
}

func _PodApi_DeletePodById0_HTTP_Handler(srv PodApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.PodId
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPodApiDeletePodById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePodById(ctx, req.(*v1.PodId))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Response)
		return ctx.Result(200, reply)
	}
}

func _PodApi_UpdatePod1_HTTP_Handler(srv PodApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.PodInfo
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPodApiUpdatePod)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePod(ctx, req.(*v1.PodInfo))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Response)
		return ctx.Result(200, reply)
	}
}

func _PodApi_Call0_HTTP_Handler(srv PodApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Request
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPodApiCall)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Call(ctx, req.(*Request))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type PodApiHTTPClient interface {
	AddPod(ctx context.Context, req *v1.PodInfo, opts ...http.CallOption) (rsp *v1.Response, err error)
	Call(ctx context.Context, req *Request, opts ...http.CallOption) (rsp *Response, err error)
	DeletePodById(ctx context.Context, req *v1.PodId, opts ...http.CallOption) (rsp *v1.Response, err error)
	FindPodById(ctx context.Context, req *v1.PodId, opts ...http.CallOption) (rsp *v1.PodInfo, err error)
	UpdatePod(ctx context.Context, req *v1.PodInfo, opts ...http.CallOption) (rsp *v1.Response, err error)
}

type PodApiHTTPClientImpl struct {
	cc *http.Client
}

func NewPodApiHTTPClient(client *http.Client) PodApiHTTPClient {
	return &PodApiHTTPClientImpl{client}
}

func (c *PodApiHTTPClientImpl) AddPod(ctx context.Context, in *v1.PodInfo, opts ...http.CallOption) (*v1.Response, error) {
	var out v1.Response
	pattern := "/v1/pod"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPodApiAddPod))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PodApiHTTPClientImpl) Call(ctx context.Context, in *Request, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/v1"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPodApiCall))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PodApiHTTPClientImpl) DeletePodById(ctx context.Context, in *v1.PodId, opts ...http.CallOption) (*v1.Response, error) {
	var out v1.Response
	pattern := "/v1/pod"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPodApiDeletePodById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PodApiHTTPClientImpl) FindPodById(ctx context.Context, in *v1.PodId, opts ...http.CallOption) (*v1.PodInfo, error) {
	var out v1.PodInfo
	pattern := "/v1/pod"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPodApiFindPodById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PodApiHTTPClientImpl) UpdatePod(ctx context.Context, in *v1.PodInfo, opts ...http.CallOption) (*v1.Response, error) {
	var out v1.Response
	pattern := "/v1/pod"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPodApiUpdatePod))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
